CREATE TABLE IF NOT EXISTS crypto_prices (
    timestamp TIMESTAMPTZ PRIMARY KEY,
    open DOUBLE PRECISION,
    high DOUBLE PRECISION,
    low DOUBLE PRECISION,
    close DOUBLE PRECISION,
    volume DOUBLE PRECISION
);